version: '3.6'
services:
  cocoa-maze-runner:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:integration-v8-cli
    environment:
      DEBUG:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_ASPECTO_REPEATER_API_KEY:
      MAZE_REPEATER_API_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
    volumes:
      - ./features/fixtures/ios/output:/app/build
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output

  cocoa-maze-runner-legacy:
    image: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:integration-v8-cli-legacy
    environment:
      DEBUG:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_REPEATER_API_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      USE_LEGACY_DRIVER: 1
    volumes:
      - ./features/fixtures/ios/output:/app/build
      - ./features/:/app/features/
      - ./maze_output:/app/maze_output
