env:
  LANG: "en_GB.UTF-8"

steps:
  - label: ":lint-roller: Lint"
    commands:
    - brew bundle install
    - brew bundle exec -- swiftlint --strict Sources
  - group: ":xcode_simulator: Test"
    steps:
      - label: "iOS 15"
        command: xcodebuild -scheme BugsnagPerformance -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' test
        agents:
          queue: macos-12-arm
      - label: "iOS 10"
        command: xcodebuild -scheme BugsnagPerformance -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' test
        agents:
          queue: macos-10.15
