env:
  LANG: "en_GB.UTF-8"

steps:
  - label: ":hammer: Example"
    command: cd Example && xcodebuild -scheme Example -destination generic/platform=iOS
    agents:
      queue: macos-12-arm
  - group: ":xcode_simulator: Test"
    steps:
      - label: "iOS 15"
        command: xcodebuild -scheme BugsnagPerformance -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' test
        agents:
          queue: macos-12-arm
      - label: "iOS 10"
        command: xcodebuild -scheme BugsnagPerformance -destination 'platform=iOS Simulator,name=iPhone 5s,OS=10.3.1' test SWIFT_VERSION=4.2
        agents:
          queue: macos-10.15
