env:
  LANG: "en_GB.UTF-8"

agents:
  queue: "macos-26"

steps:

  - group: "Builds"
    steps:
      - label: ":hammer: XCFramework"
        key: "xcframework"
        timeout_in_minutes: 10
        commands:
          - "make build_xcframework"
        env:
          XCODE_VERSION: "26.1.1"
        plugins:
          - "artifacts#v1.9.3":
              upload:
                - "BugsnagPerformance.xcframework.zip"
                - "BugsnagPerformanceSwift.xcframework.zip"
                - "BugsnagPerformanceNamedSpans.xcframework.zip"

      - label: ":hammer: Carthage"
        timeout_in_minutes: 10
        commands:
          - "bundle install"
          - "./features/fixtures/carthage/build.sh"
        env:
          XCODE_VERSION: "26.1.1"

      - label: ":hammer: CocoaPods"
        timeout_in_minutes: 10
        commands:
          - "bundle install"
          - "pod lib lint BugsnagPerformance.podspec.json"
        env:
          XCODE_VERSION: "26.1.1"

      - label: ":hammer: Example"
        timeout_in_minutes: 10
        commands:
          - "bundle install"
          - "./Example/build.sh"
        env:
          XCODE_VERSION: "26.1.1"

      - label: ":hammer: Fixture"
        key: "ios_fixture"
        timeout_in_minutes: 10
        commands:
          - "./features/fixtures/ios/build.sh"
          - "bundle install"
          - "bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bb_ipa_url.txt"
          - "bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bs_ipa_url.txt"
        env:
          XCODE_VERSION: "26.1.1"
        artifact_paths:
          - "features/fixtures/ios/output/bb_ipa_url.txt"
          - "features/fixtures/ios/output/bs_ipa_url.txt"
          - "features/fixtures/ios/output/Fixture.ipa"

      - label: ":hammer: XcFramework fixture"
        key: "ios_xcframework_fixture"
        depends_on: "xcframework"
        timeout_in_minutes: 10
        commands:
          - "./features/fixtures/ios/build_xcframework.sh"
          - "bundle install"
          - "bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureXcFramework.ipa --app-id-file=./features/fixtures/ios/output/bb_xcframework_ipa_url.txt"
          - "bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/FixtureXcFramework.ipa --app-id-file=./features/fixtures/ios/output/bs_xcframework_ipa_url.txt"
        env:
          XCODE_VERSION: "26.1.1"
        plugins:
          - "artifacts#v1.9.3":
              download:
                - "BugsnagPerformance.xcframework.zip"
                - "BugsnagPerformanceSwift.xcframework.zip"
                - "BugsnagPerformanceNamedSpans.xcframework.zip"
        artifact_paths:
          - "features/fixtures/ios/output/bb_xcframework_ipa_url.txt"
          - "features/fixtures/ios/output/bs_xcframework_ipa_url.txt"

      - label: ":hammer: Fixture swizzling disabled"
        key: "ios_fixture_swizzling_disabled"
        timeout_in_minutes: 10
        commands:
          - "./features/fixtures/ios/build.sh --disableSwizzling --fixtureName FixtureWithDisableSwizzling"
          - "bundle install"
          - "bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureWithDisableSwizzling.ipa --app-id-file=./features/fixtures/ios/output/bb_url_swizzling_disabled.txt"
          - "bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/FixtureWithDisableSwizzling.ipa --app-id-file=./features/fixtures/ios/output/bs_url_swizzling_disabled.txt"
        env:
          XCODE_VERSION: "26.1.1"
        artifact_paths:
          - "features/fixtures/ios/output/bb_url_swizzling_disabled.txt"
          - "features/fixtures/ios/output/bs_url_swizzling_disabled.txt"

      - label: ":hammer: Fixture swizzling premain"
        key: "ios_fixture_swizzling_premain"
        timeout_in_minutes: 10
        commands:
          - "./features/fixtures/ios/build.sh --swizzlingPremain --fixtureName FixtureWithSwizzlingPremain"
          - "bundle install"
          - "bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureWithSwizzlingPremain.ipa --app-id-file=./features/fixtures/ios/output/bb_url_swizzling_premain.txt"
          - "bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/FixtureWithSwizzlingPremain.ipa --app-id-file=./features/fixtures/ios/output/bs_url_swizzling_premain.txt"
        env:
          XCODE_VERSION: "26.1.1"
        artifact_paths:
          - "features/fixtures/ios/output/bb_url_swizzling_premain.txt"
          - "features/fixtures/ios/output/bs_url_swizzling_premain.txt"

      - label: ":hammer: Benchmarks fixture"
        key: "ios_fixture_benchmarks"
        timeout_in_minutes: 10
        commands:
          - "./features/fixtures/benchmarks/build.sh --fixtureName FixtureBenchmarks"
          - "bundle install"
          - "bundle exec upload-app --farm=bb --app=./features/fixtures/benchmarks/output/FixtureBenchmarks.ipa --app-id-file=./features/fixtures/benchmarks/output/bb_ipa_url_benchmarks.txt"
          - "bundle exec upload-app --farm=bs --app=./features/fixtures/benchmarks/output/FixtureBenchmarks.ipa --app-id-file=./features/fixtures/benchmarks/output/bs_ipa_url_benchmarks.txt"
        env:
          XCODE_VERSION: "26.1.1"
        artifact_paths:
          - "features/fixtures/benchmarks/output/bb_ipa_url_benchmarks.txt"
          - "features/fixtures/benchmarks/output/bs_ipa_url_benchmarks.txt"
          - "features/fixtures/benchmarks/output/FixtureBenchmarks.ipa"

  - group: "Unit tests"
    steps:
      - label: ":xcode_simulator: iOS 26 Unit Tests"
        timeout_in_minutes: 10
        commands:
          - "./scripts/run-unit-tests.sh PLATFORM=iOS OS=26.1.1 DEVICE=\"iPhone 17\""
        env:
          XCODE_VERSION: "26.1.1"
        plugins:
          "artifacts#v1.9.3":
            upload:
              - "logs/*"

      - label: ":xcode_simulator: iOS 13 Unit tests"
        timeout_in_minutes: 10
        agents:
          queue: "macos-12-arm"
        commands:
          - "./scripts/run-unit-tests.sh PLATFORM=iOS OS=13.7"
        env:
          XCODE_VERSION: "14"
        plugins:
          "artifacts#v1.9.3":
            upload:
              - "logs/*"

  - group: "e2e tests"
    steps:
      - label: ":bitbar: {{matrix}} e2e tests"
        matrix:
          - "IOS_26"
          - "IOS_13"
        depends_on:
          - "ios_fixture"
        timeout_in_minutes: 60
        agents:
          queue: "opensource"
        plugins:
          "artifacts#v1.9.3":
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          "docker-compose#v4.8.0":
            pull: "maze-runner-bb"
            run: "maze-runner-bb"
            service-ports: "true"
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device={{matrix}}"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          "test-collector#v1.10.2":
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: -1  # Agent was lost
              limit: 2
            - exit_status: 103  # Appium session failed
              limit: 2

  - group: "XcFramework e2e tests"
    steps:
      - label: ":bitbar: {{matrix}} XcFramework e2e tests"
        matrix:
          - "IOS_26"
          - "IOS_13"
        depends_on:
          - "ios_xcframework_fixture"
        timeout_in_minutes: 30
        agents:
          queue: "opensource"
        plugins:
          "artifacts#v1.9.3":
            download: "features/fixtures/ios/output/bb_xcframework_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          "docker-compose#v4.8.0":
            pull: "maze-runner-bb"
            run: "maze-runner-bb"
            service-ports: "true"
            command:
              - "--app=@build/bb_xcframework_ipa_url.txt"
              - "--device={{matrix}}"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default/automatic_spans.feature"
          "test-collector#v1.10.2":
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: -1  # Agent was lost
              limit: 2
            - exit_status: 103  # Appium session failed
              limit: 2

  - group: "Swizzling disabled e2e tests"
    steps:
      - label: ":bitbar: {{matrix}} swizzling disabled e2e tests"
        matrix:
          - "IOS_26"
          - "IOS_13"
        depends_on:
          - "ios_fixture_swizzling_disabled"
        timeout_in_minutes: 30
        agents:
          queue: "opensource"
        plugins:
          "artifacts#v1.9.3":
            download: "features/fixtures/ios/output/bb_url_swizzling_disabled.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/maze_output.zip"
              - "maze_output/metrics.csv"
          "docker-compose#v4.8.0":
            pull: "maze-runner-bb"
            run: "maze-runner-bb"
            service-ports: "true"
            command:
              - "--app=@build/bb_url_swizzling_disabled.txt"
              - "--device={{matrix}}"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/swizzling_disabled"
          "test-collector#v1.10.2":
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: -1  # Agent was lost
              limit: 2
            - exit_status: 103  # Appium session failed
              limit: 2

  - group: "Swizzling premain e2e tests"
    steps:
      - label: ":bitbar: {{matrix}} swizzling premain e2e tests"
        matrix:
          - "IOS_26"
          - "IOS_13"
        depends_on:
          - "ios_fixture_swizzling_premain"
        timeout_in_minutes: 60
        agents:
          queue: "opensource"
        plugins:
          "artifacts#v1.9.3":
            download: "features/fixtures/ios/output/bb_url_swizzling_premain.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/maze_output.zip"
              - "maze_output/metrics.csv"
          "docker-compose#v4.8.0":
            pull: "maze-runner-bb"
            run: "maze-runner-bb"
            service-ports: "true"
            command:
              - "--app=@build/bb_url_swizzling_premain.txt"
              - "--device={{matrix}}"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--exclude=features/default/automatic_spans_generic_view_load.feature"
              - "features/default"
          "test-collector#v1.10.2":
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: -1  # Agent was lost
              limit: 2
            - exit_status: 103  # Appium session failed
              limit: 2

  - group: "Benchmark tests"
    steps:
      - label: ":bitbar: {{matrix}} Benchmark tests"
        matrix:
          - "IOS_26"
          - "IOS_13"
        depends_on:
          - "ios_fixture_benchmarks"
        timeout_in_minutes: 30
        agents:
          queue: "opensource"
        plugins:
          "artifacts#v1.9.3":
            download: "features/fixtures/benchmarks/output/bb_ipa_url_benchmarks.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          "docker-compose#v4.8.0":
            pull: "maze-runner-bb"
            run: "maze-runner-bb"
            service-ports: "true"
            command:
              - "--app=@build_benchmarks/bb_ipa_url_benchmarks.txt"
              - "--device={{matrix}}"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/benchmarks"
          "test-collector#v1.10.2":
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: "bitbar-app"
        concurrency_method: "eager"
        retry:
          automatic:
            - exit_status: -1  # Agent was lost
              limit: 2
            - exit_status: 103  # Appium session failed
              limit: 2

  - label: "Conditionally trigger full set of tests"
    agents:
      queue: "macos"
    timeout_in_minutes: 2
    command: "sh -c .buildkite/pipeline_trigger.sh"
