env:
  LANG: "en_GB.UTF-8"

agents:
  queue: macos-12-arm

steps:

  - group: ":hammer:"
    steps:
      - label: "Carthage"
        command: ./features/fixtures/carthage/build.sh
      - label: "CocoaPods"
        command: pod lib lint BugsnagPerformance.podspec.json
      - label: "Example"
        command: ./Example/build.sh
      - label: "Fixture"
        command: ./features/fixtures/ios/build.sh
        key: ios_fixture
        artifact_paths:
          - features/fixtures/ios/output/Fixture.ipa

  - group: ":xcode_simulator: Unit Tests"
    steps:
      - label: "iOS 15 Unit Tests"
        commands:
          - xcodebuild -version
          - xcodebuild -scheme BugsnagPerformance-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -quiet build-for-testing
          - xcodebuild -scheme BugsnagPerformance-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' test-without-building
      - label: "iOS 11 Unit Tests"
        commands:
          - xcodebuild -version
          - xcodebuild -scheme BugsnagPerformance-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' -quiet build-for-testing SWIFT_VERSION=4.2
          - xcodebuild -scheme BugsnagPerformance-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' test-without-building
        agents:
          queue: macos-11

  - group: ":iphone: E2E Tests"
    steps:
      - label: "iOS 15 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 5
        agents:
          queue: opensource
        plugins:
          artifacts#v1.5.0:
            download: features/fixtures/ios/output/Fixture.ipa
            upload: "maze_output/failed/**/*"
          docker-compose#v3.7.0:
            pull: cocoa-maze-runner
            run: cocoa-maze-runner
            command:
              - "--app=features/fixtures/ios/output/Fixture.ipa"
              - "--appium-version=1.21.0"
              - "--device=IOS_15"
              - "--fail-fast"
              - "--farm=bs"
              - "--order=random"
        concurrency: 24
        concurrency_group: browserstack-app
        concurrency_method: eager
      - label: "iOS 11 E2E Tests"
        depends_on:
          - ios_fixture
        # More time than other steps as the BrowserStack iOS 11 devices seem particularly unstable and
        # sessions need resetting frequently, taking a minute or more each time.
        timeout_in_minutes: 10
        agents:
          queue: opensource
        plugins:
          artifacts#v1.5.0:
            download: features/fixtures/ios/output/Fixture.ipa
            upload: "maze_output/failed/**/*"
          docker-compose#v3.7.0:
            pull: cocoa-maze-runner-legacy
            run: cocoa-maze-runner-legacy
            command:
              - "--app=features/fixtures/ios/output/Fixture.ipa"
              - "--appium-version=1.8.0"
              - "--device=IOS_11"
              - "--fail-fast"
              - "--farm=bs"
              - "--order=random"
        concurrency: 24
        concurrency_group: browserstack-app
        concurrency_method: eager
