env:
  LANG: "en_GB.UTF-8"
  XCODE_VERSION: "15.3.0"

agents:
  queue: macos-14

steps:

  - group: ":hammer: Builds"
    steps:
      - label: "XCFramework"
        key: xcframework
        timeout_in_minutes: 20
        commands:
          - make build_xcframework
        plugins:
          - artifacts#v1.9.3:
              upload:
                - "BugsnagPerformance.xcframework.zip"
                - "BugsnagPerformanceSwift.xcframework.zip"

      - label: "Carthage"
        commands:
          - bundle install
          - ./features/fixtures/carthage/build.sh

      - label: "CocoaPods"
        commands:
          - bundle install
          - pod lib lint BugsnagPerformance.podspec.json

      - label: "Example"
        commands:
          - bundle install
          - ./Example/build.sh

      - label: "Fixture"
        key: ios_fixture
        commands:
          - ./features/fixtures/ios/build.sh
          - bundle install
          - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bb_ipa_url.txt
          - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bs_ipa_url.txt
        artifact_paths:
          - features/fixtures/ios/output/bb_ipa_url.txt
          - features/fixtures/ios/output/bs_ipa_url.txt

      - label: "XcFramework Fixture"
        key: ios_xcframework_fixture
        depends_on: xcframework
        commands:
          - ./features/fixtures/ios/build_xcframework.sh
          - bundle install
          - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureXcFramework.ipa --app-id-file=./features/fixtures/ios/output/bb_xcframework_ipa_url.txt
          - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/FixtureXcFramework.ipa --app-id-file=./features/fixtures/ios/output/bs_xcframework_ipa_url.txt
        plugins:
          - artifacts#v1.9.3:
              download:
                - "BugsnagPerformance.xcframework.zip"
                - "BugsnagPerformanceSwift.xcframework.zip"
        artifact_paths:
          - features/fixtures/ios/output/bb_xcframework_ipa_url.txt
          - features/fixtures/ios/output/bs_xcframework_ipa_url.txt

      - label: "Fixture swizzling disabled"
        key: ios_fixture_swizzling_disabled
        commands:
          - ./features/fixtures/ios/build.sh --disableSwizzling --fixtureName FixtureWithDisableSwizzling
          - bundle install
          - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureWithDisableSwizzling.ipa --app-id-file=./features/fixtures/ios/output/bb_url_swizzling_disabled.txt
        artifact_paths:
          - features/fixtures/ios/output/bb_url_swizzling_disabled.txt

      - label: "Fixture swizzling premain"
        key: ios_fixture_swizzling_premain
        commands:
          - ./features/fixtures/ios/build.sh --swizzlingPremain --fixtureName FixtureWithSwizzlingPremain
          - bundle install
          - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/FixtureWithSwizzlingPremain.ipa --app-id-file=./features/fixtures/ios/output/bb_url_swizzling_premain.txt
        artifact_paths:
          - features/fixtures/ios/output/bb_url_swizzling_premain.txt

  - group: ":xcode_simulator: Unit Tests"
    steps:
      - label: "iOS 17 Unit Tests"
        commands:
          - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=17.4 DEVICE="iPhone 15"
        plugins:
          artifacts#v1.9.3:
            upload:
              - "logs/*"
      - label: "iOS 13 Unit Tests"
        commands:
          - ./scripts/run-unit-tests.sh PLATFORM=iOS OS=13.7
        plugins:
          artifacts#v1.9.3:
            upload:
              - "logs/*"
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: "14"

  #
  # BitBar
  #
  - group: "E2E Tests"
    steps:
      - label: ":browserstack: iOS 18 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bs_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bs
            run: maze-runner-bs
            service-ports: true
            command:
              - "--app=@build/bs_ipa_url.txt"
              - "--device=IOS_18"
              - "--fail-fast"
              - "--farm=bs"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager

      - label: ":bitbar: iOS 16 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_16"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

      - label: ":bitbar: iOS 15 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_15"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

      - label: ":bitbar: iOS 14 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_14"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

      - label: ":bitbar: iOS 13 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_13"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

  - group: ":bitbar: XcFramework E2E Tests"
    steps:
      - label: ":browserstack: iOS XcFramework 18 E2E Tests"
        depends_on:
          - ios_xcframework_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bs_xcframework_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bs
            run: maze-runner-bs
            service-ports: true
            command:
              - "--app=@build/bs_xcframework_ipa_url.txt"
              - "--device=IOS_18"
              - "--fail-fast"
              - "--farm=bs"
              - "--exclude=features/default/automatic_spans_generic_view_load.feature"
              - "features/default/automatic_spans.feature"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager

      - label: ":bitbar: iOS XcFramework 13 E2E Tests"
        depends_on:
          - ios_xcframework_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_xcframework_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_xcframework_ipa_url.txt"
              - "--device=IOS_13"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "--exclude=features/default/automatic_spans_generic_view_load.feature"
              - "features/default/automatic_spans.feature"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

  - group: ":bitbar: Swizzling disabled E2E Tests"
    steps:
      - label: ":bitbar: iOS 16 E2E Tests swizzling disabled"
        depends_on:
          - ios_fixture_swizzling_disabled
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_url_swizzling_disabled.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_url_swizzling_disabled.txt"
              - "--device=IOS_16"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/swizzling_disabled"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

      - label: ":bitbar: iOS 14 E2E Tests swizzling disabled"
        depends_on:
          - ios_fixture_swizzling_disabled
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_url_swizzling_disabled.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_url_swizzling_disabled.txt"
              - "--device=IOS_14"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/swizzling_disabled"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

  - group: "Swizzling premain E2E Tests"
    steps:
      - label: ":browserstack: iOS 18 E2E Tests swizzling premain"
        depends_on:
          - ios_fixture_swizzling_premain
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_url_swizzling_premain.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bs
            run: maze-runner-bs
            service-ports: true
            command:
              - "--app=@build/bb_url_swizzling_premain.txt"
              - "--device=IOS_18"
              - "--fail-fast"
              - "--farm=bs"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager

      - label: ":bitbar: iOS 13 E2E Tests swizzling premain"
        depends_on:
          - ios_fixture_swizzling_premain
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_url_swizzling_premain.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_url_swizzling_premain.txt"
              - "--device=IOS_13"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh
