env:
  LANG: "en_GB.UTF-8"
  XCODE_VERSION: "15.4.0"

agents:
  queue: macos-14

steps:

  - group: ":hammer: Builds"
    steps:

      - label: "Fixture"
        key: ios_fixture
        commands:
          - ./features/fixtures/ios/build.sh
          - bundle install
          - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bb_ipa_url.txt
          - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/Fixture.ipa --app-id-file=./features/fixtures/ios/output/bs_ipa_url.txt
        artifact_paths:
          - features/fixtures/ios/output/bb_ipa_url.txt
          - features/fixtures/ios/output/bs_ipa_url.txt

  - group: "E2E Tests"
    steps:
      - label: ":bitbar: iOS 17 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_17"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager

      - label: ":browserstack: iOS 17 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bs_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bs
            run: maze-runner-bs
            service-ports: true
            command:
              - "--app=@build/bs_ipa_url.txt"
              - "--device=IOS_17"
              - "--fail-fast"
              - "--farm=bs"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 5
        concurrency_group: browserstack-app
        concurrency_method: eager

      - label: ":bitbar: iOS 13 E2E Tests"
        depends_on:
          - ios_fixture
        timeout_in_minutes: 30
        agents:
          queue: opensource
        plugins:
          artifacts#v1.9.3:
            download: "features/fixtures/ios/output/bb_ipa_url.txt"
            upload:
              - "maze_output/failed/**/*"
              - "maze_output/metrics.csv"
              - "maze_output/maze_output.zip"
          docker-compose#v4.8.0:
            pull: maze-runner-bb
            run: maze-runner-bb
            service-ports: true
            command:
              - "--app=@build/bb_ipa_url.txt"
              - "--device=IOS_13"
              - "--fail-fast"
              - "--farm=bb"
              - "--no-tunnel"
              - "--aws-public-ip"
              - "features/default"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
        concurrency: 25
        concurrency_group: bitbar-app
        concurrency_method: eager
