Feature: LoadingIndicator view to mark data loading phase

  Scenario: LoadingIndicatorViewSimpleStopScenario
    Given I run "LoadingIndicatorViewSimpleStopScenario"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait for 2 seconds
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I invoke "finishLoading"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" duration is equal or greater than 2.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewSimpleStopScenario - named
    Given I load scenario "LoadingIndicatorViewSimpleStopScenario"
    And I configure scenario "name" to "SimpleStopScenarioIndicatorName"
    And I start bugsnag
    And I run the loaded scenario
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait for 2 seconds
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I invoke "finishLoading"
    And I wait to receive a span named "SimpleStopScenarioIndicatorName"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "SimpleStopScenarioIndicatorName" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController" duration is equal or greater than 2.0
    * a span named "SimpleStopScenarioIndicatorName" duration is equal or greater than 2.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewSimpleStopScenario_ViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewSimpleRemoveScenario
    Given I run "LoadingIndicatorViewSimpleRemoveScenario"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait for 2 seconds
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I invoke "finishLoading"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" duration is equal or greater than 2.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewSimpleRemoveScenario - named
    Given I load scenario "LoadingIndicatorViewSimpleRemoveScenario"
    And I configure scenario "name" to "SimpleRemoveScenarioIndicatorName"
    And I start bugsnag
    And I run the loaded scenario
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait for 2 seconds
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I invoke "finishLoading"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    And I wait to receive a span named "SimpleRemoveScenarioIndicatorName"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "SimpleRemoveScenarioIndicatorName" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController" duration is equal or greater than 2.0
    * a span named "SimpleRemoveScenarioIndicatorName" duration is equal or greater than 2.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewSimpleRemoveScenario_ViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewNestedViewStopScenario - stop inner, outer, child
    Given I run "LoadingIndicatorViewNestedViewStopScenario"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingParentInner"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingParentOuter"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingChild"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" duration is equal or greater than 3.0
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" duration is equal or greater than 3.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewNestedViewStopScenario - stop child, inner, outer
    Given I run "LoadingIndicatorViewNestedViewStopScenario"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingChild"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I invoke "finishLoadingParentInner"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I invoke "finishLoadingParentOuter"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" duration is equal or greater than 3.0
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" duration is equal or greater than 1.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewNestedViewStopScenario - stop outer, child, inner
    Given I run "LoadingIndicatorViewNestedViewStopScenario"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingParentOuter"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingChild"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I invoke "finishLoadingParentInner"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" duration is equal or greater than 3.0
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" duration is equal or greater than 2.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"

  Scenario: LoadingIndicatorViewNestedViewStopScenario - stop outer, child, inner - named
    Given I load scenario "LoadingIndicatorViewNestedViewStopScenario"
    And I configure scenario "name1" to "NestedViewStopScenarioIndicatorName1"
    And I configure scenario "name2" to "NestedViewStopScenarioIndicatorName2"
    And I configure scenario "name3" to "NestedViewStopScenarioIndicatorName3"
    And I start bugsnag
    And I run the loaded scenario
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoadPhase/loadView]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLoad]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/View appearing]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidAppear]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewWillLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/Subview layout]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoadPhase/viewDidLayoutSubviews]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingParentOuter"
    And I wait to receive a span named "NestedViewStopScenarioIndicatorName2"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I invoke "finishLoadingChild"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    And I wait to receive a span named "NestedViewStopScenarioIndicatorName3"
    And I wait for 1 second
    * no span field "name" equals "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I invoke "finishLoadingParentInner"
    And I wait to receive a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    And I wait to receive a span named "NestedViewStopScenarioIndicatorName1"
    Then the trace "Content-Type" header equals "application/json"
    * the trace "Bugsnag-Sent-At" header matches the regex "^\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ$"
    * a span named "NestedViewStopScenarioIndicatorName1" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "NestedViewStopScenarioIndicatorName2" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "NestedViewStopScenarioIndicatorName3" is a child of span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span named "[ViewLoad/UIKit]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" ended at the same time as a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController" duration is equal or greater than 3.0
    * a span named "[ViewLoadPhase/viewDataLoading]/Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController" duration is equal or greater than 2.0
    * a span named "NestedViewStopScenarioIndicatorName1" duration is equal or greater than 4.0
    * a span named "NestedViewStopScenarioIndicatorName2" duration is equal or greater than 2.0
    * a span named "NestedViewStopScenarioIndicatorName3" duration is equal or greater than 3.0
    * every span field "spanId" matches the regex "^[A-Fa-f0-9]{16}$"
    * every span field "traceId" matches the regex "^[A-Fa-f0-9]{32}$"
    * every span field "kind" equals 1
    * every span field "startTimeUnixNano" matches the regex "^[0-9]+$"
    * every span field "endTimeUnixNano" matches the regex "^[0-9]+$"
    * a span string attribute "bugsnag.span.category" equals "view_load"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ParentViewController"
    * a span string attribute "bugsnag.view.name" equals "Fixture.LoadingIndicatorViewNestedViewStopScenario_ChildViewController"
    * a span bool attribute "bugsnag.span.first_class" is true
    * a span string attribute "bugsnag.view.type" equals "UIKit"
    * the trace payload field "resourceSpans.0.resource" string attribute "service.name" matches the regex "com.bugsnag.fixtures.cocoaperformance(xcframework)?"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.name" equals "bugsnag.performance.cocoa"
    * the trace payload field "resourceSpans.0.resource" string attribute "telemetry.sdk.version" matches the regex "[0-9]+\.[0-9]+\.[0-9]+"
